window.oracleData = {
    players: [
        {
            name: 'NexusTitan',
            title: 'Mythic II • Jungle',
            mmr: 3421,
            winRate: 64,
            kda: '6.2 / 2.1 / 8.5',
            damage: 24531,
            goldPerMin: 612,
            favoriteGod: 'Loki',
        },
        {
            name: 'AuroraForge',
            title: 'Ascendant I • Mid',
            mmr: 3298,
            winRate: 58,
            kda: '4.5 / 2.9 / 9.7',
            damage: 26654,
            goldPerMin: 598,
            favoriteGod: 'Raijin',
        },
        {
            name: 'WardenPrime',
            title: 'Mythic V • Support',
            mmr: 3510,
            winRate: 67,
            kda: '2.1 / 1.5 / 14.3',
            damage: 9832,
            goldPerMin: 501,
            favoriteGod: 'Athena',
        },
    ],
    leaderboard: [
        { rank: 1, player: 'WardenPrime', role: 'Support', mmr: 3510, wr: '67%' },
        { rank: 2, player: 'NexusTitan', role: 'Jungle', mmr: 3421, wr: '64%' },
        { rank: 3, player: 'Duality', role: 'ADC', mmr: 3388, wr: '61%' },
        { rank: 4, player: 'AuroraForge', role: 'Mid', mmr: 3298, wr: '58%' },
        { rank: 5, player: 'TerraNova', role: 'Solo', mmr: 3250, wr: '60%' },
    ],
    gods: [
        {
            name: 'Raijin',
            tier: 'S Tier • Mid',
            winRate: '55.6%',
            pickRate: '23%',
            build: ['Pendulum of Ages', 'Tablet of Destinies', 'Spear of Desolation', 'Charon\'s Coin'],
        },
        {
            name: 'Athena',
            tier: 'S Tier • Support',
            winRate: '58.9%',
            pickRate: '18%',
            build: ['Sentinel\'s Embrace', 'Prophetic Cloak', 'Sovereignty', 'Heartward Amulet'],
        },
        {
            name: 'Cernunnos',
            tier: 'A+ Tier • Hunter',
            winRate: '52.4%',
            pickRate: '29%',
            build: ['Leather Cannon', 'Silverbranch Bow', 'Dominance', 'Deathbringer'],
        },
        {
            name: 'Hecate',
            tier: 'A Tier • Jungle',
            winRate: '51.2%',
            pickRate: '15%',
            build: ['Protean Claws', 'Evolved Transcendence', 'Heartseeker', 'Brawler\'s Beat Stick'],
        },
    ],
    matches: [
        {
            result: 'Victory',
            duration: '31:24',
            mode: 'Ranked Conquest',
            teams: 'Oracle Collective vs. Titan Academy',
            mvp: 'NexusTitan (Loki)',
            kda: '12/2/11',
        },
        {
            result: 'Defeat',
            duration: '28:04',
            mode: 'Ranked Conquest',
            teams: 'Oracle Collective vs. StormBound',
            mvp: 'StormBound.Demi (Morgan Le Fay)',
            kda: '4/6/7',
        },
        {
            result: 'Victory',
            duration: '25:44',
            mode: 'Competitive Joust',
            teams: 'TriForce vs. River Spirits',
            mvp: 'TriForce.Mez (Susano)',
            kda: '9/1/6',
        },
    ],
    news: [
        {
            title: 'PTS Balance Sweep',
            description: 'Guardians receive early mitigation nerfs ahead of LAN.',
            time: '2h ago',
        },
        {
            title: 'Closed Beta #2 Invites Live',
            description: 'Hi-Rez expands testing to console cross-play.',
            time: '6h ago',
        },
        {
            title: 'Map Lighting Update',
            description: 'New dusk variant showcased during Smite 2 Direct.',
            time: '1d ago',
        },
        {
            title: 'Oracle Roadmap',
            description: 'Match API adapters ready for drop-in once endpoints launch.',
            time: '2d ago',
        },
    ],
    roadmap: [
        {
            phase: 'Now',
            title: 'Smite 2 API Integration',
            description: 'Swap mock data for the live Ranked, Match, and Profile endpoints.',
            status: 'Ready on API launch',
        },
        {
            phase: 'Next',
            title: 'Personalized Dashboards',
            description: 'Login, pin mains, and sync loadouts for quick access to builds.',
            status: 'UX mockups in review',
        },
        {
            phase: 'Next',
            title: 'Cross-Platform Match History',
            description: 'Merge PC + console timelines with filtering and share links.',
            status: 'Data modeling in progress',
        },
        {
            phase: 'Later',
            title: 'Esports Team Hubs',
            description: 'Follow pro rosters, scrim notes, and LAN predictions.',
            status: 'Exploratory research',
        },
    ],
};
